# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://adiaz-efaa.github.io/archivos_cmf/"

git_url = "https://github.com/adiaz-efaa/archivos_cmf/tree/main/"

def custom_doc_links(name): return None
