# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Fecha": "00_core.ipynb",
         "fecha": "00_core.ipynb",
         "Cadena": "00_core.ipynb",
         "cadena": "00_core.ipynb",
         "Entero": "00_core.ipynb",
         "entero": "00_core.ipynb",
         "EnteroSigno": "00_core.ipynb",
         "entero_signo": "00_core.ipynb",
         "Flotante": "00_core.ipynb",
         "flotante": "00_core.ipynb",
         "FlotanteSigno": "00_core.ipynb",
         "flotante_signo": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://adiaz-efaa.github.io/archivos_cmf/"

git_url = "https://github.com/adiaz-efaa/archivos_cmf/tree/main/"

def custom_doc_links(name): return None
